version : '3.7'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '15672:15672'

  worker:
    build: worker
    volumes:
      - ./worker:/worker

  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000

  test_mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: